# Generated by Django 2.1 on 2018-10-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='orientador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordenador.Orientador'),
        ),
        migrations.RemoveField(
            model_name='acompanhamento',
            name='orientando',
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='orientando',
            field=models.ManyToManyField(to='coordenador.Orientando'),
        ),
    ]
