# Generated by Django 2.1 on 2018-10-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0004_auto_20181010_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientando',
            name='orientador',
        ),
    ]
