# Generated by Django 2.1 on 2018-10-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0006_orientando_orientador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento',
            name='orientador',
        ),
        migrations.RemoveField(
            model_name='acompanhamento',
            name='orientando',
        ),
        migrations.RemoveField(
            model_name='orientando',
            name='orientador',
        ),
        migrations.AddField(
            model_name='orientando',
            name='orientor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientandos', to='coordenador.Orientador'),
        ),
        migrations.DeleteModel(
            name='Acompanhamento',
        ),
    ]
