# Generated by Django 2.1 on 2018-10-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
        ('historico', '0002_remove_linhadotempo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhadotempo',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentario.Comentario'),
        ),
    ]
