# Generated by Django 2.1 on 2018-10-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordenador', '0001_initial'),
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linhadotempo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historico.LinhaDotempo')),
                ('orientando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordenador.Orientando')),
            ],
            options={
                'verbose_name': 'Historico Orientador',
                'verbose_name_plural': 'Historico Orientadores',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('assunto', models.TextField(max_length=130)),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordenador.Orientador')),
                ('orientando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordenador.Orientando')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
            },
        ),
    ]
