# Generated by Django 2.1 on 2018-10-09 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordenador', '0001_initial'),
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=60)),
                ('comentario', models.TextField(max_length=160)),
                ('arquivo', models.FileField(upload_to='documents/')),
                ('linhadotempo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historico.LinhaDotempo')),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordenador.Orientador')),
            ],
            options={
                'verbose_name': 'Historico Orientando',
                'verbose_name_plural': 'Historicos Orientando',
            },
        ),
    ]
