# Generated by Django 2.1 on 2018-10-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('comentario', models.TextField(blank=True, max_length=160, null=True)),
            ],
        ),
    ]
